### PR TITLE
Add Screenshot Element option

### PR DESCRIPTION
**Pull request by wei**
Updated code and README.md  Feedback welcome!

### CODE REVIEW

**Comment by wei** [comment]
I signed it!

**Comment by aslafy-z** [comment]
It's live in here: https://fathomless-beyond-52997.herokuapp.com/

**Comment by wei** [comment]
Thanks @aslafy-z Demo: https://fathomless-beyond-52997.herokuapp.com/screenshot?url=https://www.wikipedia.org&element=.central-featured

**Review by ebidel — APPROVED** [review]
Neat. Thanks!

**Pull request merged**
