### PR TITLE
fix: ReferenceError

### PR DESCRIPTION
**Pull request by gokaygurcan**
```
ReferenceError: res is not defined
    at enableCors (/app/server.js:11:5)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:137:13)
    at next (/app/node_modules/express/lib/router/route.js:131:14)
    at next (/app/node_modules/express/lib/router/route.js:131:14)
    at next (/app/node_modules/express/lib/router/route.js:131:14)
    at next (/app/node_modules/express/lib/router/route.js:131:14)
    at next (/app/node_modules/express/lib/router/route.js:131:14)
    at next (/app/node_modules/express/lib/router/route.js:131:14)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
```

Hi, 
the website returns this error. 

I hope it'll help. 

Cheers,
G.

### CODE REVIEW

**Comment by PaulKinlan** [comment]
Urgh. I should have tested...

**Comment by PaulKinlan** [comment]
ACtually... this is totallu broke

**Comment by PaulKinlan** [comment]
Fix incoming - was being arrogant and didn't test properly

**Comment by gokaygurcan** [comment]
Hehe, happens to best of us, don't worry.

**Pull request merged**
